Try to track down a bug with streaming in Neo4j 3.2.2.
This results in an error:

    org.neo4j.index.internal.gbptree.TreeInconsistencyException: Some internal problem causing out of bounds: pageId:-1